MexIFace: mexiface::MexIFaceBase Class Reference
mexiface::MexIFaceBase Class Reference abstract
Base class defining the virtual functions that will be implemented by MexIFaceHandler and the concrete subclasses of MexIFace.
#include </home/travis/build/markjolah/MexIFace/include/MexIFace/MexIFaceBase.h>
Protected Member Functions
virtual void objConstruct ()=0
Called when the mexFunction gets the @new command, passing on the remaining input arguments.
virtual void objDestroy (const mxArray *mxhandle)=0
Called when the mexFunction gets the @delete command.
virtual void getObjectFromHandle (const mxArray *mxhandle)=0
Helper method which saves a pointer to the wrapped class's object in an internal member variable called obj.
virtual void output (mxArray *m)=0
Append a generic mxArray to the output arguments This is virtual because MexIFaceHandler need to use it to output a Handle pointer.
virtual std::string obj_name () const =0
Get the name of the class of the stored object.
virtual ~MexIFaceBase ()=default
Detailed Description
Base class defining the virtual functions that will be implemented by MexIFaceHandler and the concrete subclasses of MexIFace.
The coordination of this base class together with the MexIFace and MexIFaceHandler<T> classes allows the end user to ignore most of the particulars of error-prone object destruction and handle manipulation, but a objConstruct is still required to be overloaded in the users class.
User classes should inherit: public MexIFace, public MexIFaceHandler<T>
Definition at line 26 of file MexIFaceBase.h.
Constructor & Destructor Documentation
virtual mexiface::MexIFaceBase::~MexIFaceBase () protected virtual default
Member Function Documentation
virtual void mexiface::MexIFaceBase::getObjectFromHandle (const mxArray * mxhandle) protected pure virtual
Helper method which saves a pointer to the wrapped class's object in an internal member variable called obj.
This pure virtual function is implemented in the MexIFaceHandler class template.
Parameters
mxhandle scalar array where the handle is stored
Implemented in mexiface::MexIFaceHandler< ObjT >.
Referenced by mexiface::MexIFace::mexFunction().
virtual std::string mexiface::MexIFaceBase::obj_name () const protected pure virtual
Get the name of the class of the stored object.
Implemented in mexiface::MexIFaceHandler< ObjT >.
Referenced by mexiface::MexIFace::error().
virtual void mexiface::MexIFaceBase::objConstruct () protected pure virtual
Called when the mexFunction gets the @new command, passing on the remaining input arguments.
The rhs should have a single output argument which is the handle (number) which corresponds to the wrapped object.
This pure virtual function must be overloaded by the concrete MexIFace subclass that can use the get<> methods to take in arbitrary parameters for whatever constrctor(s) exists for that wrapped class.
Referenced by mexiface::MexIFace::mexFunction().
virtual void mexiface::MexIFaceBase::objDestroy (const mxArray * mxhandle) protected pure virtual
Called when the mexFunction gets the @delete command.
This pure virtual function is implemented in the MexIFaceHandler class template.
Parameters
mxhandle scalar array where the handle is stored
Implemented in mexiface::MexIFaceHandler< ObjT >.
Referenced by mexiface::MexIFace::mexFunction().
virtual void mexiface::MexIFaceBase::output (mxArray * m) protected pure virtual
Append a generic mxArray to the output arguments This is virtual because MexIFaceHandler need to use it to output a Handle pointer.
Parameters
m Array to append to output arguments.
Implemented in mexiface::MexIFace.
Referenced by mexiface::MexIFaceHandler< ObjT >::outputHandle().
The documentation for this class was generated from the following file:
MexIFaceBase.h