MexIFace: mexiface::MexIFaceHandler< ObjT > Class Template Reference
mexiface::MexIFaceHandler< ObjT > Class Template Reference abstract
Class encompassing the MexIFace type-dependent operations. Must be inherited from to form a concrete MexIFace. The class encapsulates the management of the Handle<T> type to hide it from the end user.
#include </home/travis/build/markjolah/MexIFace/include/MexIFace/MexIFaceHandler.h>
Protected Member Functions
MexIFaceHandler ()
void objDestroy (const mxArray *mxhandle) overridefinal
Called when the mexFunction gets the @delete command.
void getObjectFromHandle (const mxArray *mxhandle) overridefinal
Helper method which saves a pointer to the wrapped class's object in an internal member variable called obj.
std::string obj_name () const overridefinal
Get the name of the class of the stored object.
void outputHandle (ObjT *obj)
Should be called from all and only from objConstructor() overrides of MexIFace sub-classes.
virtual void objConstruct ()=0
Called when the mexFunction gets the @new command, passing on the remaining input arguments.
virtual void output (mxArray *m)=0
Append a generic mxArray to the output arguments This is virtual because MexIFaceHandler need to use it to output a Handle pointer.
Protected Attributes
ObjT * obj =nullptr
Detailed Description
template<class ObjT>
class mexiface::MexIFaceHandler< ObjT >
Class encompassing the MexIFace type-dependent operations. Must be inherited from to form a concrete MexIFace. The class encapsulates the management of the Handle<T> type to hide it from the end user.
Parameters
ObjT Wrapped C++ class type.
Definition at line 22 of file MexIFaceHandler.h.
Constructor & Destructor Documentation
template<class ObjT > mexiface::MexIFaceHandler< ObjT >::MexIFaceHandler () protected
Definition at line 57 of file MexIFaceHandler.h.
Member Function Documentation
template<class ObjT > void mexiface::MexIFaceHandler< ObjT >::getObjectFromHandle (const mxArray * mxhandle) final override protected virtual
Helper method which saves a pointer to the wrapped class's object in an internal member variable called obj.
This pure virtual function is implemented in the MexIFaceHandler class template.
Parameters
mxhandle scalar array where the handle is stored
Implements mexiface::MexIFaceBase.
Definition at line 62 of file MexIFaceHandler.h.
References mexiface::Handle< T >::getObject(), and mexiface::MexIFaceHandler< ObjT >::obj.
template<class ObjT > std::string mexiface::MexIFaceHandler< ObjT >::obj_name () const final override protected virtual
Get the name of the class of the stored object.
Implements mexiface::MexIFaceBase.
Definition at line 74 of file MexIFaceHandler.h.
virtual void mexiface::MexIFaceBase::objConstruct () protected pure virtual inherited
Called when the mexFunction gets the @new command, passing on the remaining input arguments.
The rhs should have a single output argument which is the handle (number) which corresponds to the wrapped object.
This pure virtual function must be overloaded by the concrete MexIFace subclass that can use the get<> methods to take in arbitrary parameters for whatever constrctor(s) exists for that wrapped class.
Referenced by mexiface::MexIFace::mexFunction().
template<class ObjT > void mexiface::MexIFaceHandler< ObjT >::objDestroy (const mxArray * mxhandle) final override protected virtual
Called when the mexFunction gets the @delete command.
This pure virtual function is implemented in the MexIFaceHandler class template.
Parameters
mxhandle scalar array where the handle is stored
Implements mexiface::MexIFaceBase.
Definition at line 68 of file MexIFaceHandler.h.
References mexiface::Handle< T >::destroyObject().
virtual void mexiface::MexIFaceBase::output (mxArray * m) protected pure virtual inherited
Append a generic mxArray to the output arguments This is virtual because MexIFaceHandler need to use it to output a Handle pointer.
Parameters
m Array to append to output arguments.
Implemented in mexiface::MexIFace.
Referenced by mexiface::MexIFaceHandler< ObjT >::outputHandle().
template<class ObjT > void mexiface::MexIFaceHandler< ObjT >::outputHandle (ObjT * obj) protected
Should be called from all and only from objConstructor() overrides of MexIFace sub-classes.
Takes over the memory management of the object for the remainder of its lifetime over multiple calls to the mex function until the @delete command is sent
Parameters
obj pointer to newly created object of type obj. Takes owenership of obj.
Definition at line 81 of file MexIFaceHandler.h.
References mexiface::MexIFaceBase::output().
Member Data Documentation
template<class ObjT > ObjT* mexiface::MexIFaceHandler< ObjT >::obj =nullptr protected
Definition at line 27 of file MexIFaceHandler.h.
Referenced by mexiface::MexIFaceHandler< ObjT >::getObjectFromHandle().
The documentation for this class was generated from the following file:
MexIFaceHandler.h