MexIFace: mexiface Namespace Reference
mexiface Namespace Reference
Namespaces
explore
Classes
class Handle
A class to represent and manipulate handles to C++ classes that can be wrapped as Matlab arrays, allowing C++ objects to persist between Mex calls.
class Hypercube
A class to create a 4D armadillo array that can use externally allocated memory.
class MexIFace
Base class for the C++ side of a MexIFace interface class.
class MexIFaceBase
Base class defining the virtual functions that will be implemented by MexIFaceHandler and the concrete subclasses of MexIFace.
class MexIFaceError
class MexIFaceHandler
Class encompassing the MexIFace type-dependent operations. Must be inherited from to form a concrete MexIFace. The class encapsulates the management of the Handle<T> type to hide it from the end user.
Typedefs
typedef Hypercube< double > hypercube
typedef Hypercube< float > fhypercube
Functions
const char * get_mx_class_name (mxClassID id)
Returns a string representation of the class with given mxClassID.
template<>
mxClassID get_mx_class< double > ()
template<>
mxClassID get_mx_class< float > ()
template<>
mxClassID get_mx_class< int8_t > ()
template<>
mxClassID get_mx_class< int16_t > ()
template<>
mxClassID get_mx_class< int32_t > ()
template<>
mxClassID get_mx_class< long > ()
template<>
mxClassID get_mx_class< long long > ()
template<>
mxClassID get_mx_class< uint8_t > ()
template<>
mxClassID get_mx_class< uint16_t > ()
template<>
mxClassID get_mx_class< uint32_t > ()
template<>
mxClassID get_mx_class< unsigned long long > ()
template<>
mxClassID get_mx_class< unsigned long > ()
void exploreMexArgs (int nargs, const mxArray *args[])
Given the arguments to a matlab mex function call, print out the details of each arguments.
std::string demangle (const char *name)
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
a make_unique implementation for use when compiling with C++11 std::make_unique is availible in C++14
const char * get_mx_class_name (const mxArray *array)
Returns a string representation of the mxArray class name.
template<class T >
mxClassID get_mx_class ()
Templated function to returns the matlab mxClassID for given C++ data type.
template<>
mxClassID get_mx_class< int64_t > ()
template<>
mxClassID get_mx_class< uint64_t > ()
template<class T >
std::string type_name (const T &t)
template<class T >
std::string type_name ()
Typedef Documentation
typedef Hypercube<float> mexiface::fhypercube
Definition at line 151 of file hypercube.h.
typedef Hypercube<double> mexiface::hypercube
Definition at line 150 of file hypercube.h.
Function Documentation
std::string mexiface::demangle (const char * name)
Definition at line 75 of file MexUtils.cpp.
Referenced by get_mx_class_name(), and type_name().
void mexiface::exploreMexArgs (int nargs, const mxArray * args[])
Given the arguments to a matlab mex function call, print out the details of each arguments.
Parameters
nargs Number of arguments
args Array of pointers to mxArray's that were given as arguments to a function call
Uses the explore.cpp methods as provided my Matlab. This is just an interface that is callable without using it directlty as a mexFunction.
Definition at line 64 of file MexUtils.cpp.
References mexiface::explore::analyze_class(), and mexiface::explore::get_characteristics().
Referenced by get_mx_class(), and mexiface::MexIFace::mexFunction().
template<class T > mxClassID mexiface::get_mx_class ()
Templated function to returns the matlab mxClassID for given C++ data type.
Returns
mxClassID for templated C++ class type.
Definition at line 56 of file MexUtils.h.
References exploreMexArgs().
template<> mxClassID mexiface::get_mx_class< double > ()
Templates for get_mx_class Can't use uint64_t as sometimes it may be long or long long. best to set mxClassID for long and long long individually
Definition at line 41 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< float > ()
Definition at line 42 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< int16_t > ()
Definition at line 44 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< int32_t > ()
Definition at line 45 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< int64_t > ()
template<> mxClassID mexiface::get_mx_class< int8_t > ()
Definition at line 43 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< long > ()
Definition at line 46 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< long long > ()
Definition at line 47 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< uint16_t > ()
Definition at line 49 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< uint32_t > ()
Definition at line 50 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< uint64_t > ()
template<> mxClassID mexiface::get_mx_class< uint8_t > ()
Definition at line 48 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< unsigned long > ()
Definition at line 52 of file MexUtils.cpp.
template<> mxClassID mexiface::get_mx_class< unsigned long long > ()
Definition at line 51 of file MexUtils.cpp.
const char * mexiface::get_mx_class_name (mxClassID id)
Returns a string representation of the class with given mxClassID.
Parameters
id The mxClassID to get name for
Returns
String giving name of matlab data class id.
Definition at line 15 of file MexUtils.cpp.
Referenced by mexiface::MexIFace::checkedFloatToFloatConversion(), mexiface::MexIFace::checkedFloatToIntegerConversion(), mexiface::MexIFace::checkedIntegerToFloatConversion(), mexiface::MexIFace::checkedIntegerToIntegerConversion(), mexiface::MexIFace::checkType(), get_mx_class_name(), mexiface::MexIFace::getAsBool(), mexiface::MexIFace::getAsFloat(), and mexiface::MexIFace::getAsInt().
const char * mexiface::get_mx_class_name (const mxArray * array) inline
Returns a string representation of the mxArray class name.
Parameters
array The mxArray to analyze
Returns
String giving class name of array
Definition at line 70 of file MexUtils.h.
References demangle(), and get_mx_class_name().
template<typename T , typename... Args> std::unique_ptr<T> mexiface::make_unique (Args &&... args)
a make_unique implementation for use when compiling with C++11 std::make_unique is availible in C++14
Definition at line 21 of file hypercube.h.
template<class T > std::string mexiface::type_name (const T & t)
Definition at line 78 of file MexUtils.h.
References demangle().
template<class T > std::string mexiface::type_name ()
Definition at line 80 of file MexUtils.h.
References demangle().