MexIFace: mexiface::explore Namespace Reference
mexiface::explore Namespace Reference
Functions
void analyze_cell (const mxArray *cell_array_ptr)
void analyze_structure (const mxArray *structure_array_ptr)
void analyze_string (const mxArray *string_array_ptr)
void analyze_sparse (const mxArray *array_ptr)
void analyze_int8 (const mxArray *array_ptr)
void analyze_uint8 (const mxArray *array_ptr)
void analyze_int16 (const mxArray *array_ptr)
void analyze_uint16 (const mxArray *array_ptr)
void analyze_int32 (const mxArray *array_ptr)
void analyze_uint32 (const mxArray *array_ptr)
void analyze_int64 (const mxArray *array_ptr)
void analyze_uint64 (const mxArray *array_ptr)
void analyze_single (const mxArray *array_ptr)
void analyze_double (const mxArray *array_ptr)
void analyze_logical (const mxArray *array_ptr)
void analyze_full (const mxArray *numeric_array_ptr)
void display_subscript (const mxArray *array_ptr, mwSize index)
void get_characteristics (const mxArray *array_ptr)
mxClassID analyze_class (const mxArray *array_ptr)
Function Documentation
void mexiface::explore::analyze_cell (const mxArray * cell_array_ptr)
Definition at line 29 of file explore.cpp.
References analyze_class(), display_subscript(), and get_characteristics().
Referenced by analyze_class().
mxClassID mexiface::explore::analyze_class (const mxArray * array_ptr)
Definition at line 537 of file explore.cpp.
References analyze_cell(), analyze_full(), analyze_logical(), analyze_sparse(), analyze_string(), and analyze_structure().
Referenced by analyze_cell(), analyze_structure(), and mexiface::exploreMexArgs().
void mexiface::explore::analyze_double (const mxArray * array_ptr)
Definition at line 391 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_full (const mxArray * numeric_array_ptr)
Definition at line 431 of file explore.cpp.
References analyze_double(), analyze_int16(), analyze_int32(), analyze_int64(), analyze_int8(), analyze_single(), analyze_uint16(), analyze_uint32(), analyze_uint64(), and analyze_uint8().
Referenced by analyze_class().
void mexiface::explore::analyze_int16 (const mxArray * array_ptr)
Definition at line 244 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_int32 (const mxArray * array_ptr)
Definition at line 287 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_int64 (const mxArray * array_ptr)
Definition at line 328 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_int8 (const mxArray * array_ptr)
Definition at line 202 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_logical (const mxArray * array_ptr)
Definition at line 411 of file explore.cpp.
References display_subscript().
Referenced by analyze_class().
void mexiface::explore::analyze_single (const mxArray * array_ptr)
Definition at line 370 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_sparse (const mxArray * array_ptr)
Definition at line 169 of file explore.cpp.
Referenced by analyze_class().
void mexiface::explore::analyze_string (const mxArray * string_array_ptr)
Definition at line 113 of file explore.cpp.
References display_subscript().
Referenced by analyze_class().
void mexiface::explore::analyze_structure (const mxArray * structure_array_ptr)
Definition at line 64 of file explore.cpp.
References analyze_class(), display_subscript(), and get_characteristics().
Referenced by analyze_class().
void mexiface::explore::analyze_uint16 (const mxArray * array_ptr)
Definition at line 265 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_uint32 (const mxArray * array_ptr)
Definition at line 308 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_uint64 (const mxArray * array_ptr)
Definition at line 349 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::analyze_uint8 (const mxArray * array_ptr)
Definition at line 223 of file explore.cpp.
References display_subscript().
Referenced by analyze_full().
void mexiface::explore::display_subscript (const mxArray * array_ptr, mwSize index)
Definition at line 452 of file explore.cpp.
Referenced by analyze_cell(), analyze_double(), analyze_int16(), analyze_int32(), analyze_int64(), analyze_int8(), analyze_logical(), analyze_single(), analyze_string(), analyze_structure(), analyze_uint16(), analyze_uint32(), analyze_uint64(), and analyze_uint8().
void mexiface::explore::get_characteristics (const mxArray * array_ptr)
Definition at line 486 of file explore.cpp.
Referenced by analyze_cell(), analyze_structure(), and mexiface::exploreMexArgs().