if(WIN32)
    find_library(LIBICS libics-0.dll)
else()
    find_library(LIBICS libics.so $ENV{HOME}/usr/lib)
endif()
include_directories($ENV{HOME}/usr/include)
if(WIN32)
    find_library(ZLIB_LIBRARIES zlib1.dll)
else()
    find_package(ZLIB)
endif()
if(WIN32)
    set(W64_DLLS ${W64_DLLS} libics-0.dll)
    set(W64_DLLS ${W64_DLLS} ${ZLIB_LIBRARIES})
endif()
