# MexIFace CMake build system
# Mark J. Olah (mjo@cs.unm DOT edu)
# 03-2014
#
# Windows fixup/packaging script creation function for "make install"

include (BundleUtilities)
include (GetPrerequisites)

function(fixup_linux_libs bin lib)
    get_filename_component(bin "${CMAKE_INSTALL_PREFIX}/bin/${bin}" ABSOLUTE)
    get_filename_component(lib "${CMAKE_INSTALL_PREFIX}/lib/${lib}" ABSOLUTE)

    message(STATUS "fixup_linux_libs")
    message(STATUS "Libkey is: " ${lib})
    get_filename_component(libpath ${lib} PATH)
    get_filename_component(libkey ${lib} NAME)
    message(STATUS "  lib=" ${lib})
    get_prerequisites(${lib} keys 0 1 "" "")
    if(bin)
        message(STATUS "  bin=" ${bin})
        get_prerequisites(${lib} binkeys 0 1 "" "")
        set(keys ${keys} ${binkeys})
    endif()
    foreach(key ${keys})
        message(STATUS "Working on key:" ${key})
        if(NOT key MATCHES ${libkey} AND NOT key MATCHES "libgcc_s")
            get_filename_component(libname ${key} NAME)
            set(dest ${libpath}/${libname})
            if(NOT EXISTS ${dest})
                message(STATUS "Copying: " ${key} " --> " ${dest})
                execute_process(COMMAND ${CMAKE_COMMAND} -E copy ${key} ${dest})
                if(UNIX AND NOT APPLE)
                    file(RPATH_REMOVE FILE ${dest})
                endif()
            else()
                message(STATUS "Already Present: " ${key})
            endif()
        else()
             message(STATUS "Skipping: " ${key})
        endif()
    endforeach()
endfunction()
